# https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "openais_controller"
version = "0.1.0"
edition = "2021"

[dependencies]
coap = "0.12"
yaml-rust = "0.4"
coap-lite = "0.9.1"
cbor-data = "0.8.15"
tokio = { version = "1", features = ["full"] }
